"""Employment effect calculations for the CypressBit Transportation I-O Modeling Lab.

Translates dollar output effects from the Leontief model into FTE job estimates
for direct (project-facing), indirect (supply-chain), and induced (household
spending) effects.

Mathematical reference (Sections 6.2–6.3 of the build instructions):
    jobs_direct   = emp_coeff * output_direct
    jobs_indirect = emp_coeff * indirect_output(f)
    jobs_induced  = emp_coeff * L @ household_f     [simplified prototype]
"""

from __future__ import annotations

import numpy as np

from .leontief import LeontiefModel
from .schemas import EmploymentBreakdown


def calculate_employment(
    output_by_sector: np.ndarray,
    employment_coefficients: np.ndarray,
) -> np.ndarray:
    """Convert sector-level output to FTE jobs via element-wise multiplication.

    Args:
        output_by_sector: (n,) array of gross output in dollars.
        employment_coefficients: (n,) array of FTE per dollar of output,
            aligned to the same sector order.

    Returns:
        (n,) float64 array of FTE jobs by sector.
    """
    return output_by_sector * employment_coefficients


def calculate_direct_indirect_employment(
    model: LeontiefModel,
    final_demand: np.ndarray,
    emp_coeffs: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Calculate sector-level direct and indirect FTE employment.

    Direct employment is tied to the sectors that receive project spending.
    Indirect employment is supported by the supply chain activated by that
    spending (all rounds of upstream purchases).

    Args:
        model: Constructed LeontiefModel with A and sector_ids set.
        final_demand: (n,) array of final demand in dollars (after domestic
            share adjustment if applicable).
        emp_coeffs: (n,) array of FTE per dollar, aligned to model sector order.

    Returns:
        Tuple of (direct_employment, indirect_employment), each (n,) float64.
    """
    direct = calculate_employment(final_demand, emp_coeffs)
    indirect = calculate_employment(model.indirect_output(final_demand), emp_coeffs)
    return direct, indirect


def calculate_induced_employment(
    model: LeontiefModel,
    total_output: np.ndarray,
    wage_shares: np.ndarray,
    marginal_consumption_share: float,
    consumer_spending_shares: np.ndarray,
    emp_coeffs: np.ndarray,
) -> np.ndarray:
    """Calculate sector-level induced FTE employment.

    SIMPLIFIED PROTOTYPE — not a validated Type II multiplier system.
    This approach estimates the employment supported by household spending
    of labor income generated by direct and indirect output.  It is a
    transparent demonstration of the induced-effect concept and should not
    be used as a substitute for a fully calibrated Type II I-O model.

    Steps (Section 6.3 of the build instructions):
        1. labor_income = dot(total_output, wage_shares)
        2. household_f  = labor_income * marginal_consumption_share
                          * consumer_spending_shares
        3. induced_output = model.solve(household_f)
        4. return FTE employment from induced_output

    Args:
        model: LeontiefModel used for the scenario.
        total_output: (n,) array of total gross output in dollars
            (direct + indirect, i.e. model.solve(final_demand)).
        wage_shares: (n,) array of labor compensation / gross output by sector.
        marginal_consumption_share: Fraction of new labor income that
            households spend on consumption (default 0.85 in ScenarioInput).
        consumer_spending_shares: (n,) array of household consumption
            allocation by sector; must be aligned to model sector order.
        emp_coeffs: (n,) array of FTE per dollar by sector.

    Returns:
        (n,) float64 array of induced FTE jobs by sector.
    """
    labor_income = float(np.dot(total_output, wage_shares))
    household_f = labor_income * marginal_consumption_share * consumer_spending_shares
    induced_output = model.solve(household_f)
    return calculate_employment(induced_output, emp_coeffs)


def summarize_employment(
    direct: np.ndarray,
    indirect: np.ndarray,
    induced: np.ndarray | None = None,
) -> EmploymentBreakdown:
    """Aggregate sector-level FTE arrays into an EmploymentBreakdown.

    Args:
        direct: (n,) array of direct FTE by sector.
        indirect: (n,) array of indirect FTE by sector.
        induced: (n,) array of induced FTE by sector, or None to omit.

    Returns:
        EmploymentBreakdown with summed totals.
    """
    return EmploymentBreakdown.from_sector_arrays(
        direct=direct.tolist(),
        indirect=indirect.tolist(),
        induced=induced.tolist() if induced is not None else None,
    )
