"""Reporting utilities for the CypressBit Transportation I-O Modeling Lab.

Converts ScenarioResult objects into flat DataFrames, CSV files, and Markdown
documents suitable for procurement-facing technical documentation.

Report tone follows Section 17 of the build instructions:
professional, procurement-aware, and transparent about prototype status.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from .schemas import ScenarioResult, ValidationIssue

# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------

_METHODOLOGY_MARKDOWN = """\
# CypressBit Transportation I-O Modeling Lab — Methodology Summary

*This document describes the calculation approach used in the prototype model.
Results are produced from synthetic sample data and are intended for
demonstration, validation, and software-readiness purposes only.*

---

## 1. Overview

This prototype implements a static, open Leontief Input-Output (I-O) model
calibrated to highway transportation spending.  It estimates the direct,
indirect, and (optionally) induced FTE employment effects of a given
infrastructure project expenditure.

The model uses synthetic sample data by default.  Real-world use would
require official BEA I-O tables, BLS QCEW employment data, and highway
bid-tab cost data, along with independent subject-matter review.

---

## 2. Data Inputs

| Dataset | Source (production) | Purpose |
|---|---|---|
| sectors.csv | BEA Industry Accounts | Sector definitions, gross output, employment, wage shares |
| transactions.csv | BEA Use Table (domestic) | Intermediate inter-industry flows Z |
| project_cost_mix.csv | FHWA bid-tabs / BidTabs | Spending allocation by improvement type and sector |
| consumer_spending_vector.csv | BLS Consumer Expenditure Survey | Household spending shares by sector |
| inflation_index.csv | BLS PPI / BEA price indices | Year-to-year dollar conversion factor |

---

## 3. Direct Requirements Matrix (A)

The technical coefficient matrix A represents the fraction of each purchaser
sector's gross output that is sourced as intermediate input from each supplier
sector:

    a[i,j] = z[i,j] / x[j]

where z[i,j] is the intermediate transaction flow from sector i to sector j
(in dollars) and x[j] is the total gross output of sector j (in dollars).

Computation: `A = Z / x`  (column-wise division)

Guard: any x[j] below the minimum output threshold raises an error to prevent
division by near-zero values.

---

## 4. Leontief Inverse (L)

The Leontief inverse captures all rounds of supply-chain requirements
triggered by a unit of final demand:

    L = (I - A)^{-1}

where I is the identity matrix.  The matrix (I - A) must be invertible; the
model checks the condition number against a maximum threshold and rejects
ill-conditioned matrices.

For scenario output calculations the model uses `numpy.linalg.solve` rather
than the explicit inverse to improve numerical stability:

    total_output = solve(I - A, final_demand)

The explicit inverse is also exposed for documentation and multiplier analysis.

---

## 5. Final Demand Vector (f)

Project spending is allocated to I-O sectors using the cost mix table:

    f[i] = spending * sector_share[i]

If the domestic share adjustment is enabled (prototype import-penetration
adjustment, Section 6.4):

    f[i] = spending * sector_share[i] * weighted_domestic_share[i]

where the weighted domestic share is the share-weighted average of domestic
production fractions for sector i across all cost categories.

Spending is first converted from base-year to analysis-year dollars using the
inflation index:

    adjusted_spending = spending * (index[analysis_year] / index[base_year])

---

## 6. Output Effects

    output_total[i]    = solve(I - A, f)[i]      (Leontief total output)
    output_direct[i]   = f[i]                     (project spending to sector i)
    output_indirect[i] = output_total[i] - f[i]   (supply-chain rounds)

---

## 7. Employment Effects

FTE employment is computed by applying sector employment coefficients
(FTE per dollar of gross output) to each output effect:

    e[i] = employment_fte[i] / (output_millions[i] * 1_000_000)

    jobs_direct[i]   = e[i] * output_direct[i]
    jobs_indirect[i] = e[i] * output_indirect[i]

---

## 8. Induced Employment (Simplified Prototype)

**IMPORTANT: The induced effect calculation is a simplified prototype and
should not be used as a substitute for a validated Type II multiplier model.**

The approach estimates the employment generated by household spending of
labor income from direct and indirect output:

    labor_income = dot(output_total, wage_share_by_sector)
    household_f  = labor_income * marginal_consumption_share
                   * consumer_spending_shares
    induced_output = solve(I - A, household_f)
    jobs_induced[i] = e[i] * induced_output[i]

The marginal consumption share (default: 0.85) can be adjusted at runtime.

---

## 9. Key Assumptions and Limitations

- **Synthetic data**: All sample data is illustrative.  Coefficients and
  results change when real BEA/BLS/bid-tab data is substituted.
- **Static model**: The model holds technical coefficients fixed.  It does not
  account for price changes, substitution effects, or capacity constraints.
- **Simplified induced effects**: The induced calculation is a demonstration
  and is not a validated Type II SAM-based multiplier.
- **Prototype status**: This software is an internal R&D prototype and has
  not been validated by FHWA, BEA, BLS, or any other federal agency.
- **Not a JOBMOD replacement**: This model is not an implementation of JOBMOD
  or any other official highway employment model.

---

*Generated by CypressBit Transportation I-O Modeling Lab v0.1.0*
"""


def result_to_dataframe(result: ScenarioResult) -> pd.DataFrame:
    """Convert a ScenarioResult into a flat reporting DataFrame.

    Returns a DataFrame with one TOTAL summary row (sector_id="TOTAL")
    followed by one row per sector.  All rows carry scenario-level context
    columns so any subset of the CSV remains self-contained.

    Columns (per Section 16 of the build instructions):
        scenario_name, spending_amount, adjusted_spending_amount,
        direct_jobs_fte, indirect_jobs_fte, induced_jobs_fte, total_jobs_fte,
        jobs_per_million_spending, sector_id, sector_name,
        output_effect, direct_output, indirect_output, induced_output,
        employment_fte, impact_type

    Args:
        result: Completed ScenarioResult from run_scenario().

    Returns:
        pd.DataFrame with n_sectors + 1 rows.
    """
    si = result.scenario_input
    emp = result.employment
    impact_type = (
        "direct+indirect+induced" if si.include_induced else "direct+indirect"
    )

    # Scenario-level scalars repeated on every row for CSV self-containment
    scenario_ctx: dict = {
        "scenario_name": si.scenario_name,
        "spending_amount": si.spending_amount,
        "adjusted_spending_amount": result.adjusted_spending,
        "direct_jobs_fte": emp.direct_jobs_fte,
        "indirect_jobs_fte": emp.indirect_jobs_fte,
        "induced_jobs_fte": emp.induced_jobs_fte,
        "total_jobs_fte": emp.total_jobs_fte,
        "jobs_per_million_spending": result.jobs_per_million,
    }

    # -- TOTAL summary row ---------------------------------------------------
    total_direct_out = sum(result.direct_output)
    total_indirect_out = sum(result.indirect_output)
    total_induced_out = sum(result.induced_output)
    total_output_effect = total_direct_out + total_indirect_out + total_induced_out

    total_row = {
        **scenario_ctx,
        "sector_id": "TOTAL",
        "sector_name": "All Sectors",
        "output_effect": total_output_effect,
        "direct_output": total_direct_out,
        "indirect_output": total_indirect_out,
        "induced_output": total_induced_out,
        "employment_fte": emp.total_jobs_fte,
        "impact_type": impact_type,
    }

    # -- Per-sector rows ------------------------------------------------------
    sector_rows = []
    for i, sid in enumerate(result.sector_ids):
        d_out = result.direct_output[i]
        i_out = result.indirect_output[i]
        n_out = result.induced_output[i]
        sector_rows.append(
            {
                **scenario_ctx,
                "sector_id": sid,
                "sector_name": result.sector_names[i],
                "output_effect": d_out + i_out + n_out,
                "direct_output": d_out,
                "indirect_output": i_out,
                "induced_output": n_out,
                "employment_fte": (
                    result.direct_employment[i]
                    + result.indirect_employment[i]
                    + result.induced_employment[i]
                ),
                "impact_type": impact_type,
            }
        )

    return pd.DataFrame([total_row] + sector_rows)


def write_scenario_csv(result: ScenarioResult, path: str | Path) -> None:
    """Write a ScenarioResult to a CSV file.

    Args:
        result: Completed ScenarioResult from run_scenario().
        path: Destination file path.  Parent directories are created if needed.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    df = result_to_dataframe(result)
    df.to_csv(path, index=False)


def write_methodology_summary(path: str | Path) -> None:
    """Write the model methodology summary as a Markdown file.

    Args:
        path: Destination file path.  Parent directories are created if needed.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_METHODOLOGY_MARKDOWN, encoding="utf-8")


def write_validation_report(
    issues: list[ValidationIssue], path: str | Path
) -> None:
    """Write a Markdown validation report grouping issues by severity.

    Args:
        issues: List of ValidationIssue objects from any validate_* function.
        path: Destination file path.  Parent directories are created if needed.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# CypressBit Transportation I-O Modeling Lab — Validation Report",
        "",
        "_This report summarises the results of automated data validation checks._",
        "",
    ]

    severity_order = ["error", "warning", "info"]
    severity_labels = {
        "error": "Errors",
        "warning": "Warnings",
        "info": "Informational",
    }
    severity_symbols = {"error": "❌", "warning": "⚠️", "info": "ℹ️"}

    by_severity: dict[str, list[ValidationIssue]] = {s: [] for s in severity_order}
    for issue in issues:
        if issue.severity in by_severity:
            by_severity[issue.severity].append(issue)

    if not issues:
        lines += ["## Result", "", "✅ No validation issues found.", ""]
    else:
        total = len(issues)
        n_errors = len(by_severity["error"])
        n_warn = len(by_severity["warning"])
        n_info = len(by_severity["info"])
        lines += [
            "## Summary",
            "",
            f"| Severity | Count |",
            f"|---|---|",
            f"| Errors | {n_errors} |",
            f"| Warnings | {n_warn} |",
            f"| Info | {n_info} |",
            f"| **Total** | **{total}** |",
            "",
        ]
        for sev in severity_order:
            group = by_severity[sev]
            if not group:
                continue
            sym = severity_symbols[sev]
            label = severity_labels[sev]
            lines += [f"## {sym} {label}", ""]
            for iss in group:
                lines.append(f"- **{iss.issue_type}**: {iss.description}")
            lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
